---
- block:
    - name: Check for presence of Postfix TLS public certificate (for incoming mail)
      stat:
        path: "{{ postfix_tls_cert }}"
      register: postfix_tls_certfile_result
    - name: Check for presence of Postfix TLS private key (for incoming mail)
      stat:
        path: "{{ postfix_tls_key }}"
      register: postfix_tls_keyfile_result
    - name: Set postfix SMTPD (incoming mail) TLS parameters
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^#?{{ item.name }} = '
        line: "{{ item.name }} = {{ item.value }}"
        state: present
        backup: true
      with_items:
        - { name: 'smtpd_tls_cert_file', value: '{{ postfix_tls_cert }}' }
        - { name: 'smtpd_tls_key_file', value: '{{ postfix_tls_key }}' }
        - { name: 'smtpd_use_tls', value: 'yes' }
        - { name: 'smtpd_tls_session_cache_database', value: 'btree:${data_directory}/smtpd_scache' }
        - { name: 'smtpd_tls_loglevel', value: '1' }
        - { name: 'smtpd_tls_received_header', value: 'yes' }
        - { name: 'smtpd_tls_security_level', value: 'may' }
        - { name: 'smtpd_tls_protocols', value: '!SSLv2, !SSLv3' }
      notify: reload postfix
      when: postfix_tls_certfile_result.stat.exists
        and postfix_tls_keyfile_result.stat.exists
  when:
    postfix_tls_cert is defined
    and postfix_tls_key is defined
